### ISSUE TITLE
Headers for "Read" and "Play" are different sizes

### ISSUE THREAD

**Issue by turion** [jefgodesky/thefifthworld-react#27]
This is visually confusing when navigating from "Read" to "Play" or vice versa. If the different sizes are intended, consider adding a CSS transformation (like e.g. scaling) from one to the other.

**Comment by jefgodesky** [comment]
Thanks for the report. Can you send a screenshot, possibly? I’m not seeing it — they both seem like the same size whenever I look at it.

**Comment by jefgodesky** [comment]
Hi, @turion — I'm still not really sure what you're referring to. Can you send a screenshot, or maybe go into more detail about where you're seeing this? I'm seeing both headers at 95.2px. Do you mean the fact that at that size "Roleplaying Game" takes two lines, whereas "Stories" only takes one?

**Comment by turion** [comment]
I can't reproduce it, unfortunately. Not sure what was going wrong the first time I loaded it.
